### ISSUE TITLE
Does it possible to add "watermark" image for screenshot?

### ISSUE THREAD

**Issue by andirey** [daattali/shinyscreenshot#1]
Thank Dean for the great package!
It will be also cool to have the ability to add a "watermark" image for downloaded plots.
Thanks!

**Comment by daattali** [comment]
The image that's downloaded directly from shinyscreenshot to the user cannot be modified. However, you can achieve this once https://github.com/daattali/shinyscreenshot/issues/3 is implemented by taking the resulting file (that would reside on the server side) and manipulating that image with a package like [{magick}](https://cran.r-project.org/package=magick) and then offering that file to the user as a different download button.
