### ISSUE TITLE
Mac - Ubuntu compatibility

### ISSUE THREAD

**Issue by choiceMaster-ai** [daattali/shinyscreenshot#11]
Hi Dean. All well in your world I hope. 
I am using shinyscreenshot version 0.1.0.9000 on Mac Big Sur 11.5.2. The following construct works exactly as I want: save the screen shot to the given filename so that I can reference and include in RMarkdown pdf document:

shinyscreenshot::screenshot(
               selector = ".ratings",
               filename = filename,
               id = "",
               scale = 1,
               timer = 0,        
               download = FALSE,
               server_dir = ".")

However, the identical code when executed on Ubuntu shinyscreenshot version 0.1.0 fails with: 
**Warning: Error in shinyscreenshot::screenshot: unused arguments (download = FALSE, server_dir = ".")**
Any advice/suggestions on how to achieve platform compatibility? I do not want to automatically download the screenshot, simply save it for future documentation use.
Thanks.

**Comment by daattali** [comment]
I see the versions aren't the same. IIRC, these parameters are new and not on the CRAN version. Try updating.

**Comment by choiceMaster-ai** [comment]
Thanks. What is IIRC? How do I update and from where?

**Comment by daattali** [comment]
If I recall correctly. https://github.com/daattali/shinyscreenshot#installation goes over how to install; if you install from CRAN you won't have these functions, if you install the development version you will.

**Comment by choiceMaster-ai** [comment]
i did install the development version and that version caters for the necessary additional arguments. However, now the output file is not created and no message is provided. The function works on Mac and when deployed on shinyapps.io.

**Comment by daattali** [comment]
This isn't a mac-ubuntu compatibility issue - please open a new issue and include a minimal reproducible sample code. It will not be possible to understand the exact issue you face without a reprex.
