### ISSUE TITLE
save screenshot in server?

### ISSUE THREAD

**Issue by jfvalenzuelas** [daattali/shinyscreenshot#12]
Hi,

is there any chance to save the screenshot in the server, instead of triggering the download?

I've read the documentation and the "server_dir" parameter does not work or maybe it is deprecated?

The reason for this is that I need to generate a PDF with the screenshots and I would need to save the files so I can construct the PDF later on.

do you know some alternative to this?

Thanks!

**Comment by daattali** [comment]
It works in the development version if you install the package form github. It's not yet on CRAN
