### ISSUE TITLE
Parameter for download option?

### ISSUE THREAD

**Issue by jfvalenzuelas** [daattali/shinyscreenshot#13]
Would it be possible to add a parameter to enable or disable the file download trigger?

**Use case**
- Screenshot needs to be stored in server but the download should not be triggered
- The screenshot or screenshots will be used to generate another kind of file that will be download later on.

It would be maybe nice to have.

Cheers!
Jaime

**Comment by daattali** [comment]
That is already supported. As mentioned in https://github.com/daattali/shinyscreenshot/issues/12  please download the latest version and read the documentation. There is a `download=TRUE/FALSE` option.
