### ISSUE TITLE
Issues with leaflet legend

### ISSUE THREAD

**Issue by cfholbert** [daattali/shinyscreenshot#14]
Hi

Thanks for writing this great library. I use it to generate screenshots of contour maps created using leaflet. However, in the saved images, the legend appears as a single color instead of a continuous color scale. Additionally, the legend is missing the labels. Not sure why.
![ContourMap_Grape_5_Event_1_nszd](https://user-images.githubusercontent.com/31901247/141028665-7596d124-7473-4441-97a8-c44db1137277.png)
y.

**Comment by daattali** [comment]
This is an issue with the underlying screenshoting tool. As mentioned in the README, every screenshot tool has its own limitations, and the one used in this package is known to have some problems with leaflet. There's nothing much to do about that, if it isn't working properly then it isn't going to. I suggest looking in the README for alternative packages to try.
