### ISSUE TITLE
Adding multiple elements of Shiny app to Screenshot results in overextended map

### ISSUE THREAD

**Issue by amholtz** [daattali/shinyscreenshot#15]
Hello, I am using shinyscreenshot for a shiny app that I have. Specifically I am using:

div(
      id = 'mapout',
      h2(textOutput(ns("title"))),
      h3(paste0("Reporting Week: ", reporting.week)),
      leafletOutput(ns("mapsReg_outNew"), height = 700),
      h6(textOutput(ns("footnotes")))
    ),

screenshotButton(id = 'mapout', 
                     filename = paste0("case&death_", reporting.week))

When I use screenshotButton in this way with the div(), my leafletOutput map is overextending its borders. If I change id to be id= "mapsReg_outNew", the map is saved as it should be and as it is portrayed on the shinyapp. Attached you will find three files. 

Is there something I am going wrong or is this a known limitation of using screenshot? Thank you :)

Files:
EXPECTED (This is screenshot done from functionality of my laptop -mac)
![MacScreenshot](https://user-images.githubusercontent.com/17280223/144285197-b020e8c7-e390-4b23-a8c0-32a265cedb9c.png)

This is the screenshot produced using the screenshot button using the div() for multiple elements
![case death_2021-39 (3)](https://user-images.githubusercontent.com/17280223/144285054-f0863108-db4b-4033-a4e2-d59fa7a7866e.png)

This is the screenshot produced using the screenshot button for just the Map item 
![ScreenshotButton_MapOnly](https://user-images.githubusercontent.com/17280223/144285607-3a92067b-fb66-4d39-b82a-bf70133e925c.png)

**Comment by daattali** [comment]
Leaflet maps are a known limitation, they sometimes work and sometimes don't. See answer [here](https://github.com/daattali/shinyscreenshot/issues/14#issuecomment-964793887)
