### ISSUE TITLE
Leaflet legend is not correctly rendered in screenshot

### ISSUE THREAD

**Issue by roman-tremmel** [daattali/shinyscreenshot#19]
Assuming this small app

```
library(shiny)
library(leaflet)
library(shinyscreenshot)

shinyApp(
    ui = fluidPage(
    leafletOutput("map"),
    screenshotButton(id = "map")),

  server = function(input, output){
    output$map <- renderLeaflet({
     leaflet(data) %>%
       addTiles() %>% 
       addLegend("bottomright", pal = colorNumeric("viridis", 1:10), values = 1:10)
   }) 
}) 
```

Legend and map are nicely rendered within the app. 

![image](https://user-images.githubusercontent.com/28730827/189075272-c57f9205-202d-4dd0-b802-4ef619de3745.png)

When making a screenshot the legend misses the numbers and the color scale is wrong. Is this a problem of shinyscreenshot? 

![image](https://user-images.githubusercontent.com/28730827/189075511-823b13ed-1d4f-43ed-b7c8-daa7c5711fc2.png)

**Comment by daattali** [comment]
The library that is used for taking screenshots is known to have various issues with leaflet. There's not much to do about it unfortunately, you can look at the "similar packages" section in the README and try the others to see if they work - each screenshot library has certain limitations

**Comment by roman-tremmel** [comment]
Thanks for the quick reply. Will check the others.

**Comment by roman-tremmel** [comment]
Ended up using mapview's mapshot function like this. Its really slow, but it works. Note, the leaflet map has to be reactive. 

```
# ui:
            downloadButton(outputId = "dl_leaflet", label = "Screenshot", icon = icon("camera")),
# server:
            library(mapview)
            output$dl_leaflet <- downloadHandler(
                       filename = "leaflet_plot.png", 
                              content = function(file) {
                              mapshot(x = rv$leaflet_plot, 
                                             file = file, 
                                             cliprect = "viewport",
                                             selfcontained = FALSE)
             })
```
