### ISSUE TITLE
filename argument

### ISSUE THREAD

**Issue by huckleberryslim** [daattali/shinyscreenshot#2]
Awesome package Dean.

With the 'filename' argument, is there a way to specify a pathname as part of the string?  So it is not automatically saved in whatever the current working directory is?

Thank you for all you do!

**Comment by daattali** [comment]
That's literally not  possible for security reasons. The directory where the downloaded file will be placed is up to the user and their browser. A website cannot decide where to place a downloaded file.

**Comment by huckleberryslim** [comment]
apologies, i meant on the server-side.  looks like you are looking into this already, thanks again!
