### ISSUE TITLE
Leaflet shifted in screenshot

### ISSUE THREAD

**Issue by schistef** [daattali/shinyscreenshot#22]
Hey,

the leaflet map is not placed correctly in the screenshot.

Original app:
![app_original](https://user-images.githubusercontent.com/78012153/220671824-4ae9feae-16e3-457e-a8df-2d452a20391c.JPG)

screenshot:
![shifted_leaflet](https://user-images.githubusercontent.com/78012153/220672572-007c298d-1818-4164-ba72-3e3b75383c22.JPG)

**Comment by daattali** [comment]
Unfortunately, the answer here will be the same as the other issues regarding leaflet ( #14 #16 #19 ): As mentioned in the README, every screenshot tool has its own limitations, and the one used in this package is known to have some problems with leaflet. There's nothing much to do about that, if it isn't working properly then it isn't going to. I suggest looking in the README for alternative packages to try.
