### ISSUE TITLE
issue when using in DT table with rowsGroup 

### ISSUE THREAD

**Issue by Yousuf28** [daattali/shinyscreenshot#23]
Hi Dean, 
Thanks for all the useful packages you created and making them open-source. 
I am using this package to take a screenshot of DT table. 
It works fine for regular DT table. But, when I use rowsGroup argument in rendering DT table it does not work for me. 
Are there any workaround for that?

__this without using rowsGroup:__  

![shinyscreenshot (11)](https://user-images.githubusercontent.com/31291716/222269051-37e92134-a45f-4746-86c7-100aa85f90cb.png)

__this when I use rowsGroup:__  

![shinyscreenshot (12)](https://user-images.githubusercontent.com/31291716/222269075-ae297479-2f7d-4a06-bbac-64cb9b05bdaf.png)

not sure this will help but this is part of the code that used to display the table using DT package.  
rowsGroup argument in line 28.  

```
 output$table_01 <- DT::renderDT({
    data <- getData()
    clin_dose <- clin_data(data)
    if (clin_dose>0) {
    plotData_tab <- dt_01()
    color_band <- c('gray','#feb24c','#fd8d3c','#fc4e2a','#e31a1c','#b10026')
    plotData_tab <- DT::datatable(plotData_tab, rownames = FALSE,
                              class = "cell-border stripe",
                              filter = list(position = 'top'),
                              extensions = list("Buttons" = NULL,
                                                "ColReorder" = NULL),
                              caption = htmltools::tags$caption(
                                style = "caption-side: top; text-align: center; font-size: 20px; color: black",
                                "Table :", htmltools::strong("Nonclinical Findings of Potential Clinical Relevance")
                              ),
                              options = list(
                                dom = "lfrtipB",
                                buttons = c("csv", "excel", "copy", "print"),
                                colReorder = TRUE,
                                scrollY = TRUE,
                                pageLength = 25,
                                columnDefs = list(list(className = "dt-center", targets = "_all"),
                                                  list(targets = 5, visible = FALSE)),
                                initComplete = DT::JS(
                                  "function(settings, json) {",
                                  "$(this.api().table().header()).css({'background-color': '#000', 'color': '#fff'});",
                                  "}"),
                                rowsGroup = list(0,1,2))) %>%
      DT::formatStyle(columns = colnames(plotData_tab), `font-size` = "18px") %>%
      DT::formatStyle("Clinical Exposure Margin","color_noael",
                      backgroundColor = styleEqual(c(2,3,4,5,6,7),color_band))
    path <- dt_extension # folder containing dataTables.rowsGroup.js
    dep <- htmltools::htmlDependency(
      "RowsGroup", "2.0.0",
      path, script = "dataTables.rowsGroup.js")
    plotData_tab$dependencies <- c(plotData_tab$dependencies, list(dep))
    plotData_tab
  }})
```

**Comment by daattali** [comment]
Thanks for the report, but unfortunately any issues like this are a result of the underlying javascript library `html2canvas` not being perfect, and that's not something I can fix in the package. I suggest you try the alternative packages mentioned in the README and hopefully one of them will work for your usecase!

**Comment by Yousuf28** [comment]
Thanks for the response. I will try both packages.

**Comment by Yousuf28** [comment]
In case anyone else have similar issue, capture package works perfectly for my use case (DT  table  with rowsGroup) that I shared previous comment. 
 - [capture](https://github.com/dreamRs/capture)
Thanks @daattali for mentioning those package.
