### ISSUE TITLE
Some input not shown in screenshots

### ISSUE THREAD

**Issue by vnijs** [daattali/shinyscreenshot#4]
I don't know if you have seen `snapper` but it is a packages that has some similar features. I was hoping that `shinyscreenshot` could capture more input types. See example output below. The first screenshot below was capture "manually" and the 2nd through `shinyscreenshot`. As you can see the text in the text input is not shown and the multiple selection is not captured. If you have any ideads on how this could be addressed I'd be very interested.

Thanks!

First screenshot (manual):

![image](https://user-images.githubusercontent.com/2998956/100424571-9fafb780-3042-11eb-843d-3de0a3debcba.png)

Second screenshot (shinyscreenshot):

![image](https://user-images.githubusercontent.com/2998956/100424550-9888a980-3042-11eb-94fb-11fbbfaf38a9.png)

https://github.com/yonicd/snapper/issues/4

**Comment by daattali** [comment]
Seems like you already found this issue half a year ago :) https://github.com/niklasvh/html2canvas/issues/1595

Yoni's and mine packages do differ in some aspects and don't always take the same screenshots, but under the hood we both use html2canvas so this is going to be an issue until that's fixed

**Comment by vnijs** [comment]
Thanks for checking @daattali.

**Comment by vnijs** [comment]
In case this is of interest to you, I found a way to fully capture text in textAreas and all variables in multi-selects (without selectize). 

https://stackoverflow.com/questions/75576148/vertical-cropping-of-screenshot-after-applying-changes-during-onclone-html2canv

**Comment by daattali** [comment]
Thanks for remembering to come back here! I prefer not to do any monkey patching of a different library inside a package; if the suggested fix gets into html2canvas then I'll happily upgrade

**Comment by vnijs** [comment]
Understood. The html2canvas issue has been open since Sep 17, 2019 though so not sure if/when this might be addressed.

**Comment by daattali** [comment]
Fair. If you have a clean piece of code that can be injected into the codebase here, and it should not negatively affect any other behaviour, I'd be happy for a PR. No pressure, if you're too busy for that I completely understand

**Comment by vnijs** [comment]
Not likely. My setup only needs "body". Yours requires a lot more flexibility.
