### ISSUE TITLE
Enable the option for background color

### ISSUE THREAD

**Issue by jsr-code** [daattali/shinyscreenshot#6]
Hi,

Thanks for your great work on this library.

Can I suggest you add an option to change background color?
The white color usually makes modern dashboards in shinydashboard a bit difficult to screenshot due to a default theme of white boxes placed on a colored background.
html2canvas has an easy argument (backgroundColor) which could be set by a new parameter.

I tested the below code in shinyscreenshot.js and it was perfect for transparent background.

`html2canvas(
      element, {
        scale : params.scale,
        logging : false,
        useCORS : true,
        backgroundColor: "rgba(0,0,0,0)"
      }`

I don't think there's a huge need for HEX color codes, even just inputting e.g. "rgba(255,20,200,255)" as a string would be very useful.

Many thanks :-)

**Comment by daattali** [comment]
Can you show an example of where having a background on the screenshot comes in handy?
