### ISSUE TITLE
Nothing in screenshot

### ISSUE THREAD

**Issue by mmullinsm** [daattali/shinyscreenshot#8]
I set up a map with a layer of data using mapdeck and shiny and the visual output kicks out to a google chrome tab at the 127.0.0.1 random port number. So far, so good. I tried both shinyscreenshot and the button version and both work but neither produces a png file with the map - the file is blank, except for the button showing in the button version. Do you have any thoughts about why I can see the map in chrome but am unable to capture it in a png?

**Comment by daattali** [comment]
Unfortunately as is the case with any tool that tries to convert html to png, it does not always work. https://github.com/daattali/shinyscreenshot#limitations . It would be great if there was a consistent standard robust way to do this, but there isn't.

You can try other screenshot tools and see if another one does work. All the methods fail in some cases, the one I implemented seems to work for the most cases according to my tests.

**Comment by mmullinsm** [comment]
Thanks so much for the prompt response!
