### ISSUE TITLE
Weird Behavior with Shinydashboard

### ISSUE THREAD

**Issue by TaarSirion** [daattali/shinyscreenshot#9]
I noticed that shinyscreenshot behaves weird when used with shinydashboard.
From fiddling about I noticed that the elements in the dashboardbody get pushed behind the dashboardsidebar. But I have no idea how to fix it, or what to do about it.

Minimal Example:

```R
library(shiny)
library(shinydashboard)
library(shinyscreenshot)
ui <- dashboardPage(
  header = dashboardHeader(),
  sidebar = dashboardSidebar(),
  body = dashboardBody(
    actionButton("save", "Save")
  )
)

server <- function(input, output, session){
  observeEvent(input$save, {
    screenshot(selector = "body", filename = "test.png")
  })
}
```

**Comment by daattali** [comment]
Hmm I can't replicate.

Here's the screenshot I get from your code

![test png](https://user-images.githubusercontent.com/952340/114828159-92982880-9d97-11eb-89ab-137deacc1aad.png)

That said, it is entirely possible that the screenshot mechanism isn't working on your system/browser. There is no standard for taking screenshots of html pages, and as mentioned in the README, this will break in some cases. Every software tool out there that tries to do this works in some cases and breaks in others - if you find this doesn't work for your usecase, please try the other screenshot R packages I mention in the readme.
